# Generated by Django 6.0.3 on 2026-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('published_at', models.DateField()),
                ('reading_time', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('AI/ML', 'AI/ML'), ('Full-Stack', 'Full-Stack'), ('Systems', 'Systems'), ('Frontend', 'Frontend')], max_length=20)),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI/ML', 'AI/ML'), ('DevOps', 'DevOps')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('project', 'Project')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
